"string"
"this is another string"
"This is a much longer string, also with symbols inside. But that's no big deal, right? Because flex handles that for us!"
"3"
"for"
" /* this one was obvious, right? */ "
" "
""
"a \"fun\" example"
