
enum yytokentype {
  NUMBER = 260,
  PLUS = 261,
  STAR = 262
};

extern int yylval;  // token attribute
extern char* yytext;  // generated by lex/flex

int yylex();    /* will be generated by lex/flex */
