#ifndef M1_GLOBAL_H
#define M1_GLOBAL_H

#include  "global.h"

/* -------------------- global variables -------------------- */

/* global const variables */
const int BUFFER_LIST_SIZE_LIMIT;
const int REPRESENTATION_SIZE_LIMIT;

/* generated by lex/flex */
char *yytext;
int yylineno;

char *curfilename;
char *token_str;
int err_lineno;

/* -------------------- global methods -------------------- */

/* generated by lex/flex */
int yylex();

/* global methods */
int newfile(char *fn);
int popfile(void);
int terminate();
int newmacro(char* ident);

#endif