#ifndef M1_GLOBAL_H
#define M1_GLOBAL_H

#include  "global.h"

/* -------------------- global variables -------------------- */

/* global const variables */
extern const int BUFFER_LIST_SIZE_LIMIT;
extern const int REPRESENTATION_SIZE_LIMIT;

/* generated by lex/flex */
extern char *yytext;
extern int yylineno;

extern char *curfilename;
extern char *token_str;
extern int err_lineno;

/* -------------------- global methods -------------------- */

/* generated by lex/flex */
extern int yylex();

/* global methods */
extern int newfile(char *fn);
extern int popfile(void);
extern int terminate();
extern int newmacro(char* ident);

#endif