#ifndef GLOBAL_H
#define GLOBAL_H

/* -------------------- global variables -------------------- */

/* generated by lex/flex */
extern char *yytext;
extern int yylineno;

/* global variables */
extern int debug;

extern char *curfilename;
extern char *token_str;
extern int err_lineno;

/* -------------------- global methods -------------------- */

/* generated by lex/flex */
extern int yylex();

/* global methods */
extern int newfile(char *fn);
extern int popfile(void);
extern int terminate();
extern void print(const char *format, ...);
extern void addmacro(char *sym);
extern int newmacro(char* ident);

void printusage();
void printversion();

#endif